import './extension/album'
import './extension/artist'
import './extension/banner'
import './extension/comment'
import './extension/dj'
import './extension/login'
import './extension/lyric'
import './extension/music'
import './extension/personalized'
import './extension/playlist'
import './extension/recommend'
export { SearchType } from './extension/search'
import './extension/simi'
import './extension/top'
export { UserRecordType } from './extension/user'

export * from './lib/error'

export { MusicClient } from './client'
