export { MusicClient } from './client'

export * from './lib/error'

import './extension/album'
import './extension/artist'
import './extension/banner'
export { ResourceType } from './extension/comment'
import './extension/dj'
import './extension/login'
import './extension/lyric'
import './extension/music'
import './extension/personalized'
export { PlaylistOperation } from './extension/playlist'
import './extension/recommend'
export { SearchType } from './extension/search'
import './extension/simi'
export * from './extension/top'
export { UserRecordType } from './extension/user'
